server:
  port: 8082

spring:
  application:
    name: game-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/scribble # ← localhost for IntelliJ
      database: scribble
  kafka:
    bootstrap-servers: localhost:9092             # ← localhost for IntelliJ
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: game-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.pm.*"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/