server:
  port: 8765

spring:
  zipkin:
    base-url: http://localhost:9411
  application:
    name: "api-gateway"
  main:
    web-application-type: REACTIVE
  cloud:
    gateway:
      default-filters:
        - name: RequestRateLimiter
          args:
            redis-rate-limiter:
              replenish-rate: 100
              burst-capacity: 200
              requested-tokens: 1
            key-resolver: "#{@ipKeyResolver}"
#  For a multiplayer game with 8 players sending ~10 strokes/sec each, that's 80 req/sec peak
      routes:
        - id: chat-service-route
          uri: lb://chat-service
          predicates:
            - Path=/chat/**
          filters:
#            - StripPrefix=1
#            - JwtValidation

        - id: chat-service-ws
          uri: lb://chat-service
          predicates:
            - Path=/ws-chat/**

        - id: user-service-route
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - RemoveRequestHeader=X-Request-RateLimit

        - id: game-service-route
          uri: lb://game-service
          predicates:
            - Path=/game/**
          filters:
#            - StripPrefix=1
#            - JwtValidation

        - id: drawing-service-route
          uri: lb://drawing-service
          predicates:
            - Path=/draw/**
          filters:
#            - StripPrefix=1
#            - JwtValidation

        - id: score-service-route
          uri: lb://score-service
          predicates:
            - Path=/score/**
          filters:
#            - StripPrefix=1
#            - JwtValidation

        - id: word-service-route
          uri: lb://word-service
          predicates:
            - Path=/word/**
          filters:
#            - StripPrefix=1
#            - JwtValidation

        - id: drawing-service-ws
          uri: lb://drawing-service
          predicates:
            - Path=/ws/**


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: ${JWT_SECRET:dev-secret-key-change-in-production-256bit}

gateway:
  whitelist:
    - /user/auth/register
    - /user/auth/login
    - /actuator/health
    - /ws/**


management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always   # shows DB, Redis, Kafka status in /health
  health:
    circuitbreakers:
      enabled: true           # shows Resilience4j state in /health
  tracing:
    sampling:
      probability: 1.0