spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/scribble   # ← postgres is the docker service name

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/