spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/scribble_users   # ← postgres is the docker service name
  data:
    redis:
      host: scribble-redis

management:
  zipkin:
    tracing:
      endpoint: http://scribble-zipkin:9411/api/v2/spans

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/