server:
  port: 8080

spring:
  application:
    name: chat-service
  data:
    redis:
      host: localhost    # ← localhost for IntelliJ
      port: 6379
      timeout: 2000ms
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: drawing-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.pm.*"
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always   # shows DB, Redis, Kafka status in /health
  health:
    circuitbreakers:
      enabled: true           # shows Resilience4j state in /health
  tracing:
    sampling:
      probability: 1.0

resilience4j:
  retry:
    instances:
      kafka-consumer:
        max-attempts: 3
        wait-duration: 500ms
        retry-exceptions:
          - org.springframework.dao.TransientDataAccessException
          - org.springframework.data.redis.RedisConnectionFailureException
          - java.io.IOException
