server:
  port: 8081

spring:
  application:
    name: drawing-service
  data:
    redis:
      host: localhost    # ← localhost for IntelliJ
      port: 6379
      timeout: 2000ms
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: drawing-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.pm.*"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/